### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by hakavlad** [xvitaly/zswap-cli#2]
How to build it for Debian 9?

**Comment by hakavlad** [comment]
Could you provide Makefile, please?

**Comment by xvitaly** [comment]
> How to build it for Debian 9?

```
mkdir build
cd build
cmake --build ..
```

**Comment by hakavlad** [comment]
```
user@PC:/tmp/zswap-cli/build$ cmake --build ..
Error: could not load cache
```

**Comment by ElXreno** [comment]
@hakavlad I build `zswap-cli` by following these steps:
```
mkdir build && cd build
cmake ..
cmake --build .
```

**Comment by xvitaly** [comment]
> How can I fix it?

First run cmake configure: `cmake ..`, then `cmake --build .`

**Comment by xvitaly** [comment]
I will add documentation soon. The work is almost completed.

**Comment by wanfuse123** [comment]
git submodule update --recursive --remote at root of cloned repository , the submodules are missing...
