### ISSUE TITLE
Typographical error: "accept_threhsold_percent"?

### ISSUE THREAD

**Issue by nmmanx** [xvitaly/zswap-cli#84]
### Question

Hi @xvitaly,

It's me again :).

I don't know why there are so many `threhsold` typo errors in the project:
```
accept_threhsold_percent => buggy
ZSwapAcceptThrehsoldPercentName
ZSWAP_ACCEPT_THREHSOLD_PERCENT_VALUE
...
```
Actually, there was a similar typo error in the kernel 5.6 zswap's documentation but it was fixed since 5.8-rc1 ([commit](https://github.com/torvalds/linux/commit/9469b390720460c1fca26b1ab3343bd70f7d5f5d#diff-6da4a7776821eabdd3330ccc89aaa38e4e5a7aea7c0e81e6f69260b61397a1c3)). It's just a document error, and the zswap module export the correct `sysfs` filename at first ([commit](https://github.com/torvalds/linux/commit/45190f01dd402112d3d22c0ddc4152994f9e1e55#diff-2c352e34733b0e565d862001604888560465f21e39e9fe6c0f0c781dd64cecc9)).

Hope that you fix it soon or I can help you. Thank you!

**Comment by xvitaly** [comment]
Many thanks. Will fix it.
