### ISSUE TITLE
Should handle accept_threshold_percent for kernel before 5.6

### ISSUE THREAD

**Issue by nmmanx** [xvitaly/zswap-cli#85]
### Feature request

Hi @xvitaly,

According to the mainline source code, `accept_threshold_percent` is first implemented in 5.6-rc1 ([commit](https://github.com/torvalds/linux/commit/45190f01dd402112d3d22c0ddc4152994f9e1e55)). So, on my machine running Ubuntu 18.04 LTS (kernel 5.4), zswap-cli returns:
```
ZSwap enabled: N.
Same filled pages enabled: Y.
Maximum pool percentage: 20.
Compression algorithm: lzo.
Kernel's zpool type: zbud.
Accept threhsold percentage: .
```
I think the tool should indicate whether this feature is supported or not by the current kernel, and appropriately handle it in both cases.

Thanks you for reading!

**Comment by xvitaly** [comment]
Sure. I want to add a special check before trying to read/write to `accept_threshold_percent` and throw an exception.
